### ISSUE TITLE
Use pngjs2 in order to support multiple bit depths and interlace

### ISSUE THREAD

**Issue by lukeapage** [chenglou/png-diff#5]
pngjs2 is a bugfixed pngjs with exactly the same interface, so upgrading should be easy.

**Comment by chenglou** [comment]
I'm actually pretty newb at this and coded it for my specific use-case. What are the ramification of supporting multiple bit depths and interlace? Does the comparison of this library change in any way?

**Comment by lukeapage** [comment]
no, the usage and output of the package is the same (it up or downscales it to 8-bit)

**Comment by chenglou** [comment]
Published as 0.3.1. Ping me if there's any error.
